SOLUTION_PREFIX = "sn"
SOLUTION_NAME = "sharkninja"
SEGMENTS = ["all-segments"]
PINECONE_API_KEY = ""
PINECONE_ENV = "us-east-1-aws"
PINECONE_INDEX_METRIC = "cosine"
# EMBEDDING_MODEL_DIMENSIONS = 1536
EMBEDDING_MODEL_DIMENSIONS = 384
